package com.windcity.yefeng.yfsms.data.model;

import android.os.Parcel;
import android.os.Parcelable;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by yefeng on 27/07/2017.
 */
@Entity
public class Contact implements Parcelable {
    public static final Creator<Contact> CREATOR = new Creator<Contact>() {
        @Override
        public Contact createFromParcel(Parcel source) {
            return new Contact(source);
        }

        @Override
        public Contact[] newArray(int size) {
            return new Contact[size];
        }
    };
    @Id
    public long id;
    public String address;
    public String name;
    public String avatar;

    @Generated(165210964)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Contact(long id, String address, String name, String avatar) {
        this.id = id;
        this.address = address;
        this.name = name;
        this.avatar = avatar;
    }


    @Generated(672515148)
    public Contact() {
    }

    protected Contact(Parcel in) {
        this.id = in.readLong();
        this.address = in.readString();
        this.name = in.readString();
        this.avatar = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeString(this.address);
        dest.writeString(this.name);
        dest.writeString(this.avatar);
    }
}
