package com.windcity.yefeng.yfsms.data.model;

import android.os.Parcel;
import android.os.Parcelable;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by yefeng on 19/07/2017.
 */

@Entity
public class Conversation implements Parcelable {
    public static final Creator<Conversation> CREATOR = new Creator<Conversation>() {
        @Override
        public Conversation createFromParcel(Parcel source) {
            return new Conversation(source);
        }

        @Override
        public Conversation[] newArray(int size) {
            return new Conversation[size];
        }
    };
    @Id
    public long id;
    public String name;
    public String address;
    public String newestContent;
    public long newestTime;
    public int newestProtocol;
    public long newestSmsId;
    public int totalNum;
    public int unreadNum;
    public long tabsId;
    public boolean isCheck;

    @Generated(548820907)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Conversation(long id, String name, String address, String newestContent,
            long newestTime, int newestProtocol, long newestSmsId, int totalNum,
            int unreadNum, long tabsId, boolean isCheck) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.newestContent = newestContent;
        this.newestTime = newestTime;
        this.newestProtocol = newestProtocol;
        this.newestSmsId = newestSmsId;
        this.totalNum = totalNum;
        this.unreadNum = unreadNum;
        this.tabsId = tabsId;
        this.isCheck = isCheck;
    }


    @Generated(1893991898)
    public Conversation() {
    }

    protected Conversation(Parcel in) {
        this.id = in.readLong();
        this.name = in.readString();
        this.address = in.readString();
        this.newestContent = in.readString();
        this.newestTime = in.readLong();
        this.newestProtocol = in.readInt();
        this.newestSmsId = in.readLong();
        this.totalNum = in.readInt();
        this.unreadNum = in.readInt();
        this.tabsId = in.readLong();
        this.isCheck = in.readByte() != 0;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeString(this.name);
        dest.writeString(this.address);
        dest.writeString(this.newestContent);
        dest.writeLong(this.newestTime);
        dest.writeInt(this.newestProtocol);
        dest.writeLong(this.newestSmsId);
        dest.writeInt(this.totalNum);
        dest.writeInt(this.unreadNum);
        dest.writeLong(this.tabsId);
        dest.writeByte(this.isCheck ? (byte) 1 : (byte) 0);
    }
}
