package com.windcity.yefeng.yfsms.data.model;

import android.os.Parcel;
import android.os.Parcelable;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;

/**
 * Created by yefeng on 19/07/2017.
 */
@Entity
public class Sms implements Parcelable {
    public static final Creator<Sms> CREATOR = new Creator<Sms>() {
        @Override
        public Sms createFromParcel(Parcel source) {
            return new Sms(source);
        }

        @Override
        public Sms[] newArray(int size) {
            return new Sms[size];
        }
    };
    @Id(assignable = true)
    public long id;
    public long tabsId;
    public long conversationId;
    public boolean isSpam;
    public boolean isStar;
    public boolean isDelete;
    //sms db property
    public long _id;
    public long thread_id;
    public String address;
    public String person;
    public long date;
    public int protocol;
    public int read;
    public int status;
    public int type;
    public String body;
    public String service_center;
    public String name;

    @Generated(1036649197)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public Sms(long id, long tabsId, long conversationId, boolean isSpam, boolean isStar,
            boolean isDelete, long _id, long thread_id, String address, String person,
            long date, int protocol, int read, int status, int type, String body,
            String service_center, String name) {
        this.id = id;
        this.tabsId = tabsId;
        this.conversationId = conversationId;
        this.isSpam = isSpam;
        this.isStar = isStar;
        this.isDelete = isDelete;
        this._id = _id;
        this.thread_id = thread_id;
        this.address = address;
        this.person = person;
        this.date = date;
        this.protocol = protocol;
        this.read = read;
        this.status = status;
        this.type = type;
        this.body = body;
        this.service_center = service_center;
        this.name = name;
    }


    @Generated(172684796)
    public Sms() {
    }

    protected Sms(Parcel in) {
        this.id = in.readLong();
        this.tabsId = in.readLong();
        this.conversationId = in.readLong();
        this.isSpam = in.readByte() != 0;
        this.isStar = in.readByte() != 0;
        this.isDelete = in.readByte() != 0;
        this._id = in.readLong();
        this.thread_id = in.readLong();
        this.address = in.readString();
        this.person = in.readString();
        this.date = in.readLong();
        this.protocol = in.readInt();
        this.read = in.readInt();
        this.status = in.readInt();
        this.type = in.readInt();
        this.body = in.readString();
        this.service_center = in.readString();
        this.name = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeLong(this.id);
        dest.writeLong(this.tabsId);
        dest.writeLong(this.conversationId);
        dest.writeByte(this.isSpam ? (byte) 1 : (byte) 0);
        dest.writeByte(this.isStar ? (byte) 1 : (byte) 0);
        dest.writeByte(this.isDelete ? (byte) 1 : (byte) 0);
        dest.writeLong(this._id);
        dest.writeLong(this.thread_id);
        dest.writeString(this.address);
        dest.writeString(this.person);
        dest.writeLong(this.date);
        dest.writeInt(this.protocol);
        dest.writeInt(this.read);
        dest.writeInt(this.status);
        dest.writeInt(this.type);
        dest.writeString(this.body);
        dest.writeString(this.service_center);
        dest.writeString(this.name);
    }
}

